controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

create_user:
    path: /users
    controller: App\Controller\UserController::post
    methods: POST

get_user:
    path: /users/{id}
    controller: App\Controller\UserController::get
    methods: GET

get_users:
    path: /users
    controller: App\Controller\UserController::getCollection
    methods: GET

put_user:
    path: /users/{id}
    controller: App\Controller\UserController::put
    methods: PUT

update_user:
    path: /users/{id}
    controller: App\Controller\UserController::patch
    methods: PATCH

delete_user:
    path: /users/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE